In [57]:
from FermionicHamiltonian import*
from FermionicOperator import*

In [30]:
H2_Hamiltonian = FermionicHamiltonian(molecule_geometry = [['H', [0, 0, 0]], ['H', [0, 0, 1.4]]], zeta_dict={'H': 1.24})
HHe_Hamiltonian = HartreeFock(molecule_geometry = [['H', [0, 0, 0]], ['He', [0, 0, 1.4632]]], zeta_dict={'H': 1.24, 'He': 2.0925})

In [3]:
set([ list(e.rep.keys())[0] for e in H2_Hamiltonian.fermionic_hamiltonian.rep])

{((0, 1), (0, 0)),
 ((0, 1), (0, 1), (0, 0), (0, 0)),
 ((0, 1), (0, 1), (2, 0), (2, 0)),
 ((0, 1), (1, 1), (0, 0), (1, 0)),
 ((0, 1), (1, 1), (2, 0), (3, 0)),
 ((0, 1), (2, 1), (0, 0), (2, 0)),
 ((0, 1), (2, 1), (2, 0), (0, 0)),
 ((0, 1), (3, 1), (0, 0), (3, 0)),
 ((0, 1), (3, 1), (2, 0), (1, 0)),
 ((1, 1), (0, 1), (1, 0), (0, 0)),
 ((1, 1), (0, 1), (3, 0), (2, 0)),
 ((1, 1), (1, 0)),
 ((1, 1), (1, 1), (1, 0), (1, 0)),
 ((1, 1), (1, 1), (3, 0), (3, 0)),
 ((1, 1), (2, 1), (1, 0), (2, 0)),
 ((1, 1), (2, 1), (3, 0), (0, 0)),
 ((1, 1), (3, 1), (1, 0), (3, 0)),
 ((1, 1), (3, 1), (3, 0), (1, 0)),
 ((2, 1), (0, 1), (0, 0), (2, 0)),
 ((2, 1), (0, 1), (2, 0), (0, 0)),
 ((2, 1), (1, 1), (0, 0), (3, 0)),
 ((2, 1), (1, 1), (2, 0), (1, 0)),
 ((2, 1), (2, 0)),
 ((2, 1), (2, 1), (0, 0), (0, 0)),
 ((2, 1), (2, 1), (2, 0), (2, 0)),
 ((2, 1), (3, 1), (0, 0), (1, 0)),
 ((2, 1), (3, 1), (2, 0), (3, 0)),
 ((3, 1), (0, 1), (1, 0), (2, 0)),
 ((3, 1), (0, 1), (3, 0), (0, 0)),
 ((3, 1), (1, 1), (1, 0), (3, 0))

In [58]:
import qulacs
from openfermion.transforms import get_fermion_operator, jordan_wigner
from openfermion import get_sparse_operator
from openfermion import MolecularData
from openfermionpyscf import run_pyscf

from scipy.optimize import minimize
from pyscf import fci
import numpy as np
import matplotlib.pyplot as plt


basis = "sto-3g"
multiplicity = 1
charge = 0
distance  = 0.7414
geometry = [["H", [0,0,0]],["H", [0,0,distance]]]
description  = "tmp"
molecule = MolecularData(geometry, basis, multiplicity, charge, description)
molecule = run_pyscf(molecule,run_scf = 1,run_fci = 1)
#molecule = run_pyscf(molecule, run_scf=1)
n_qubit = molecule.n_qubits
n_electron = molecule.n_electrons
fermionic_hamiltonian = get_fermion_operator(molecule.get_molecular_hamiltonian())
jw_hamiltonian = jordan_wigner(fermionic_hamiltonian)

In [123]:
of_op = {
    ((0, 1), (0, 1), (0, 0), (0, 0)): 0.3372443831784192,
    ((0, 1), (0, 1), (2, 0), (2, 0)): 0.09064440410574806,
    ((0, 1), (1, 1), (1, 0), (0, 0)): 0.3372443831784192,
    ((0, 1), (1, 1), (3, 0), (2, 0)): 0.09064440410574806,
    ((0, 1), (2, 1), (0, 0), (2, 0)): 0.09064440410574806,
    ((0, 1), (2, 1), (2, 0), (0, 0)): 0.3317340482117842,
    ((0, 1), (3, 1), (1, 0), (2, 0)): 0.09064440410574806,
    ((0, 1), (3, 1), (3, 0), (0, 0)): 0.3317340482117842,
    ((1, 1), (0, 1), (0, 0), (1, 0)): 0.3372443831784192,
    ((1, 1), (0, 1), (2, 0), (3, 0)): 0.09064440410574806,
    ((1, 1), (1, 1), (1, 0), (1, 0)): 0.3372443831784192,
    ((1, 1), (1, 1), (3, 0), (3, 0)): 0.09064440410574806,
    ((1, 1), (2, 1), (0, 0), (3, 0)): 0.09064440410574806,
    ((1, 1), (2, 1), (2, 0), (1, 0)): 0.3317340482117842,
    ((1, 1), (3, 1), (1, 0), (3, 0)): 0.09064440410574806,
    ((1, 1), (3, 1), (3, 0), (1, 0)): 0.3317340482117842,
    ((2, 1), (0, 1), (0, 0), (2, 0)): 0.3317340482117844,
    ((2, 1), (0, 1), (2, 0), (0, 0)): 0.09064440410574806,
    ((2, 1), (1, 1), (1, 0), (2, 0)): 0.3317340482117844,
    ((2, 1), (1, 1), (3, 0), (0, 0)): 0.09064440410574806,
    ((2, 1), (2, 1), (0, 0), (0, 0)): 0.09064440410574806,
    ((2, 1), (2, 1), (2, 0), (2, 0)): 0.34869688371151397,
    ((2, 1), (3, 1), (1, 0), (0, 0)): 0.09064440410574806,
    ((2, 1), (3, 1), (3, 0), (2, 0)): 0.34869688371151397,
    ((3, 1), (0, 1), (0, 0), (3, 0)): 0.3317340482117844,
    ((3, 1), (0, 1), (2, 0), (1, 0)): 0.09064440410574806,
    ((3, 1), (1, 1), (1, 0), (3, 0)): 0.3317340482117844,
    ((3, 1), (1, 1), (3, 0), (1, 0)): 0.09064440410574806,
    ((3, 1), (2, 1), (0, 0), (1, 0)): 0.09064440410574806,
    ((3, 1), (2, 1), (2, 0), (3, 0)): 0.34869688371151397,
    ((3, 1), (3, 1), (1, 0), (1, 0)): 0.09064440410574806,
    ((3, 1), (3, 1), (3, 0), (3, 0)): 0.34869688371151397,
    }

In [83]:
of = {((0, 1), (0, 1), (0, 0), (0, 0)), 
((0, 1), (0, 1), (2, 0), (2, 0)), 
((0, 1), (1, 1), (1, 0), (0, 0)), 
((0, 1), (1, 1), (3, 0), (2, 0)), 
((0, 1), (2, 1), (0, 0), (2, 0)), 
((0, 1), (2, 1), (2, 0), (0, 0)), 
((0, 1), (3, 1), (1, 0), (2, 0)), 
((0, 1), (3, 1), (3, 0), (0, 0)), 
((1, 1), (0, 1), (0, 0), (1, 0)), 
((1, 1), (0, 1), (2, 0), (3, 0)), 
((1, 1), (1, 1), (1, 0), (1, 0)), 
((1, 1), (1, 1), (3, 0), (3, 0)), 
((1, 1), (2, 1), (0, 0), (3, 0)), 
((1, 1), (2, 1), (2, 0), (1, 0)), 
((1, 1), (3, 1), (1, 0), (3, 0)), 
((1, 1), (3, 1), (3, 0), (1, 0)), 
((2, 1), (0, 1), (0, 0), (2, 0)), 
((2, 1), (0, 1), (2, 0), (0, 0)), 
((2, 1), (1, 1), (1, 0), (2, 0)), 
((2, 1), (1, 1), (3, 0), (0, 0)), 
((2, 1), (2, 1), (0, 0), (0, 0)), 
((2, 1), (2, 1), (2, 0), (2, 0)), 
((2, 1), (3, 1), (1, 0), (0, 0)), 
((2, 1), (3, 1), (3, 0), (2, 0)), 
((3, 1), (0, 1), (0, 0), (3, 0)), 
((3, 1), (0, 1), (2, 0), (1, 0)), 
((3, 1), (1, 1), (1, 0), (3, 0)), 
((3, 1), (1, 1), (3, 0), (1, 0)), 
((3, 1), (2, 1), (0, 0), (1, 0)), 
((3, 1), (2, 1), (2, 0), (3, 0)), 
((3, 1), (3, 1), (1, 0), (1, 0)), 
((3, 1), (3, 1), (3, 0), (3, 0))}

In [77]:
molecule.get_molecular_hamiltonian().two_body_tensor[0.5 * ab ==0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.33724438,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.0906444 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.0906444 , 0.        , 0.        , 0.        , 0.33173405,
       0.        , 0.        , 0.        , 0.        , 0.33724438,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.0906444 , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [66]:
molecule.two_body_integrals.round(10)

array([[[[ 0.67448877, -0.        ],
         [-0.        ,  0.18128881]],

        [[-0.        ,  0.18128881],
         [ 0.6634681 ,  0.        ]]],


       [[[-0.        ,  0.6634681 ],
         [ 0.18128881, -0.        ]],

        [[ 0.18128881, -0.        ],
         [ 0.        ,  0.69739377]]]])

In [87]:
mine = {
 ((0, 1), (0, 1), (0, 0), (0, 0)),
 ((0, 1), (0, 1), (2, 0), (2, 0)),
 ((0, 1), (1, 1), (0, 0), (1, 0)),
 ((0, 1), (1, 1), (2, 0), (3, 0)),
 ((0, 1), (2, 1), (0, 0), (2, 0)),
 ((0, 1), (2, 1), (2, 0), (0, 0)),
 ((0, 1), (3, 1), (0, 0), (3, 0)),
 ((0, 1), (3, 1), (2, 0), (1, 0)),
 ((1, 1), (0, 1), (1, 0), (0, 0)),
 ((1, 1), (0, 1), (3, 0), (2, 0)),
 ((1, 1), (1, 1), (1, 0), (1, 0)),
 ((1, 1), (1, 1), (3, 0), (3, 0)),
 ((1, 1), (2, 1), (1, 0), (2, 0)),
 ((1, 1), (2, 1), (3, 0), (0, 0)),
 ((1, 1), (3, 1), (1, 0), (3, 0)),
 ((1, 1), (3, 1), (3, 0), (1, 0)),
 ((2, 1), (0, 1), (0, 0), (2, 0)),
 ((2, 1), (0, 1), (2, 0), (0, 0)),
 ((2, 1), (1, 1), (0, 0), (3, 0)),
 ((2, 1), (1, 1), (2, 0), (1, 0)),
 ((2, 1), (2, 1), (0, 0), (0, 0)),
 ((2, 1), (2, 1), (2, 0), (2, 0)),
 ((2, 1), (3, 1), (0, 0), (1, 0)),
 ((2, 1), (3, 1), (2, 0), (3, 0)),
 ((3, 1), (0, 1), (1, 0), (2, 0)),
 ((3, 1), (0, 1), (3, 0), (0, 0)),
 ((3, 1), (1, 1), (1, 0), (3, 0)),
 ((3, 1), (1, 1), (3, 0), (1, 0)),
 ((3, 1), (2, 1), (1, 0), (0, 0)),
 ((3, 1), (2, 1), (3, 0), (2, 0)),
 ((3, 1), (3, 1), (1, 0), (1, 0)),
 ((3, 1), (3, 1), (3, 0), (3, 0))}

TypeError: 'set' object is not subscriptable

In [117]:
mine_op = {list(s.rep.keys())[0]: list(s.rep.values())[0] for s in (H2_Hamiltonian.fermionic_hamiltonian.rep)}

In [132]:
overlap_mine = {k: round(mine_op[k], 3) for k in list(mine & of)}

In [133]:
overlap_of = {k: round(of_op[k], 3) for k in list(mine & of)}

In [134]:
overlap_mine

{((0, 1), (0, 1), (2, 0), (2, 0)): 0.091,
 ((2, 1), (0, 1), (0, 0), (2, 0)): 0.091,
 ((0, 1), (0, 1), (0, 0), (0, 0)): 0.337,
 ((2, 1), (0, 1), (2, 0), (0, 0)): 0.332,
 ((1, 1), (1, 1), (3, 0), (3, 0)): 0.091,
 ((3, 1), (3, 1), (1, 0), (1, 0)): 0.091,
 ((2, 1), (2, 1), (2, 0), (2, 0)): 0.349,
 ((3, 1), (1, 1), (3, 0), (1, 0)): 0.332,
 ((0, 1), (2, 1), (0, 0), (2, 0)): 0.332,
 ((2, 1), (2, 1), (0, 0), (0, 0)): 0.091,
 ((3, 1), (1, 1), (1, 0), (3, 0)): 0.091,
 ((3, 1), (3, 1), (3, 0), (3, 0)): 0.349,
 ((1, 1), (3, 1), (3, 0), (1, 0)): 0.091,
 ((1, 1), (3, 1), (1, 0), (3, 0)): 0.332,
 ((1, 1), (1, 1), (1, 0), (1, 0)): 0.337,
 ((0, 1), (2, 1), (2, 0), (0, 0)): 0.091}

In [140]:
{
    k: (v, overlap_of[k]) for k, v in overlap_mine.items()
    if v != overlap_of[k]
}

{((2, 1), (0, 1), (0, 0), (2, 0)): (0.091, 0.332),
 ((2, 1), (0, 1), (2, 0), (0, 0)): (0.332, 0.091),
 ((3, 1), (1, 1), (3, 0), (1, 0)): (0.332, 0.091),
 ((0, 1), (2, 1), (0, 0), (2, 0)): (0.332, 0.091),
 ((3, 1), (1, 1), (1, 0), (3, 0)): (0.091, 0.332),
 ((1, 1), (3, 1), (3, 0), (1, 0)): (0.091, 0.332),
 ((1, 1), (3, 1), (1, 0), (3, 0)): (0.332, 0.091),
 ((0, 1), (2, 1), (2, 0), (0, 0)): (0.091, 0.332)}

In [141]:
{
    k: (v, overlap_of[k]) for k, v in overlap_mine.items()
    if v == overlap_of[k]
}

{((0, 1), (0, 1), (2, 0), (2, 0)): (0.091, 0.091),
 ((0, 1), (0, 1), (0, 0), (0, 0)): (0.337, 0.337),
 ((1, 1), (1, 1), (3, 0), (3, 0)): (0.091, 0.091),
 ((3, 1), (3, 1), (1, 0), (1, 0)): (0.091, 0.091),
 ((2, 1), (2, 1), (2, 0), (2, 0)): (0.349, 0.349),
 ((2, 1), (2, 1), (0, 0), (0, 0)): (0.091, 0.091),
 ((3, 1), (3, 1), (3, 0), (3, 0)): (0.349, 0.349),
 ((1, 1), (1, 1), (1, 0), (1, 0)): (0.337, 0.337)}

In [56]:
ab = zeros((4, 4, 4, 4))
for i, j, k, l in product(*([range(4)]*4)):
    
    spin_i, spin_j, spin_k, spin_l = i % 2, j % 2, k % 2, l % 2
    space_i, space_j, space_k, space_l = i // 2, j // 2, k // 2, l // 2
    
    ab[i, j, k, l] += H2_Hamiltonian.psi_AB_4_tensor[space_i, space_j, space_k, space_l] * (spin_i == spin_k) * (spin_j == spin_l)

sum([
    ab[i, j, k, l].round(5) * SingleFermionicOperator(operator_tup=((i, 1), (j, 1), (k, 0), (l, 0)), coefficient = 1)
    for i, j, k, l in product(*([range(4)]*4))
])/2

((0, 1), (3, 1), (2, 0), (1, 0)): 0.090635
((3, 1), (3, 1), (3, 0), (3, 0)): 0.348765
((1, 1), (1, 1), (1, 0), (1, 0)): 0.337305
((2, 1), (2, 1), (0, 0), (0, 0)): 0.090635
((3, 1), (2, 1), (1, 0), (0, 0)): 0.090635
((0, 1), (2, 1), (0, 0), (2, 0)): 0.331795
((3, 1), (1, 1), (1, 0), (3, 0)): 0.090635
((1, 1), (0, 1), (3, 0), (2, 0)): 0.090635
((2, 1), (1, 1), (2, 0), (1, 0)): 0.331795
((1, 1), (3, 1), (3, 0), (1, 0)): 0.090635
((2, 1), (0, 1), (0, 0), (2, 0)): 0.090635
((2, 1), (3, 1), (0, 0), (1, 0)): 0.090635
((2, 1), (0, 1), (2, 0), (0, 0)): 0.331795
((0, 1), (1, 1), (0, 0), (1, 0)): 0.337305
((0, 1), (2, 1), (2, 0), (0, 0)): 0.090635
((1, 1), (1, 1), (3, 0), (3, 0)): 0.090635
((1, 1), (2, 1), (1, 0), (2, 0)): 0.331795
((1, 1), (0, 1), (1, 0), (0, 0)): 0.337305
((3, 1), (0, 1), (1, 0), (2, 0)): 0.090635
((2, 1), (1, 1), (0, 0), (3, 0)): 0.090635
((2, 1), (2, 1), (2, 0), (2, 0)): 0.348765
((3, 1), (3, 1), (1, 0), (1, 0)): 0.090635
((0, 1), (0, 1), (2, 0), (2, 0)): 0.090635
((3, 1), (0

In [142]:
np.diag(array([[1, 2], [3, 4]]))

array([1, 4])

In [144]:
array([[1, 2], [3, 4]])[:, 0].reshape(2, 1)

array([[1],
       [3]])

In [147]:
array([[1, 2], [3, 4]]).argmin(1)

array([0, 0])

In [155]:
xxx = array([[1, 2, 3], [7, 8, 9], [4, 5, 6]])
np.argpartition(diag(xxx), 0)

array([0, 1, 2])

In [161]:
xxx

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [164]:
xxx[:, diag(xxx).argsort()[:3]]

array([[1, 3, 2],
       [7, 9, 8],
       [4, 6, 5]])