In [1]:
import numpy as np
from numpy import array
import mpmath as mp
from sympy import Rational, I, Matrix, conjugate
from Quantum_Gate_np import*

In [2]:
CNOT = QuantumGate(n = 2, free_bits_dict={}, target_bits_dict={1: X}, controlled_bits_dict={0: 1})

In [3]:
%timeit QuantumGate(n = 4, free_bits_dict={}, target_bits_dict={2*1+1: X}, controlled_bits_dict={2*1: 1})
%timeit QuantumGate_old(n = 4, free_bits_dict={}, target_bits_dict={2*1+1: X}, controlled_bits_dict={2*1: 1})

344 µs ± 76.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
31.8 ms ± 3.46 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
RRR = RZ(theta = pi/3) @ RY(theta = pi/3)

In [6]:
g1 = QuantumGate(n = 4, free_bits_dict={0: RRR}, target_bits_dict={2*1+1: X}, controlled_bits_dict={2*1: 1}).matrix_rep
g2 = QuantumGate_old(n = 4, free_bits_dict={0: RRR}, target_bits_dict={2*1+1: X}, controlled_bits_dict={2*1: 1}).matrix_rep
(g1 == g2).all()

True

In [1]:
tmptmptmp = QuantumGate(n = 4, free_bits_dict={0: RRR}, target_bits_dict={}, controlled_bits_dict={})

NameError: name 'QuantumGate' is not defined

In [6]:
tmptmptmp.matrix_rep

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j,
        0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.

In [20]:
%timeit QuantumGate(n = 4, free_bits_dict={0: RRR}, target_bits_dict={1: X}, controlled_bits_dict={2: 0, 3: 1})
%timeit QuantumGate_old(n = 4, free_bits_dict={0: RRR}, target_bits_dict={1: X}, controlled_bits_dict={2: 0, 3: 1})

293 µs ± 3.33 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
28.5 ms ± 2.93 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [16]:
g1 = QuantumGate(n = 4, free_bits_dict={0: RRR}, target_bits_dict={1: X}, controlled_bits_dict={2: 0, 3: 1})
g2 = QuantumGate_old(n = 4, free_bits_dict={0: RRR}, target_bits_dict={1: X}, controlled_bits_dict={2: 0, 3: 1})

In [17]:
(g1.matrix_rep == g2.matrix_rep).all()

True

In [8]:
30e-3/335e-6

89.55223880597015

In [17]:
list(QuantumGate(n = 4, free_bits_dict={0: RRR}, target_bits_dict={1: X}, controlled_bits_dict={2: 0}).operator_list)

[array([[ 0.75     +0.4330127j,  0.4330127+0.25j     ],
        [-0.4330127+0.25j     ,  0.75     -0.4330127j]]),
 array([[0, 1],
        [1, 0]]),
 array([[1., 0.],
        [0., 1.]]),
 array([[1., 0.],
        [0., 1.]])]

In [21]:
QuantumGate_old(n = 4, free_bits_dict={0: RRR}, target_bits_dict={1: X}, controlled_bits_dict={2: 0, 3: 1}).free_bits_dict

{0: array([[ 0.75     +0.4330127j,  0.4330127+0.25j     ],
        [-0.4330127+0.25j     ,  0.75     -0.4330127j]])}

In [19]:
(QuantumGate(n = 4, free_bits_dict={}, target_bits_dict={1: X}, controlled_bits_dict={2: 0, 3: 1}).compute_matrix_rep() - QuantumGate_old(n = 4, free_bits_dict={}, target_bits_dict={1: X}, controlled_bits_dict={2: 0, 3: 1}).matrix_rep)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [9]:
(6.88e-6/52.9e-3)**-1

7688.9534883720935

In [16]:
(QuantumGate(n = 4, free_bits_dict={}, target_bits_dict={2*1+1: X}, controlled_bits_dict={2*1: 1}).compute_matrix_rep() == QuantumGate_old(n = 4, free_bits_dict={}, target_bits_dict={2*1+1: X}, controlled_bits_dict={2*1: 1}).matrix_rep).all()

True

In [14]:
QuantumGate_old(n = 4, free_bits_dict={}, target_bits_dict={2*1+1: X}, controlled_bits_dict={2*1: 1}).matrix_rep

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [8]:
%timeit CNOT.compute_matrix_rep()

85.1 µs ± 11.8 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [9]:
%%timeit
QuantumGate_old(n = 2, free_bits_dict={}, target_bits_dict={1: X}, controlled_bits_dict={0: 1})

1.47 ms ± 516 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
for i in range(2):
    print((i not in CNOT.free_bits_dict) and (i not in CNOT.target_bits_dict) and (i not in CNOT.controlled_bits_dict))

False
False


In [12]:
(
    (x:=1) not in CNOT.controlled_bits_dict, 
    (x not in CNOT.target_bits_dict), 
    (x not in CNOT.controlled_bits_dict)
) 

(True, False, True)

In [4]:
CNOT.operator_list

dict_values([array([[0, 1],
       [1, 0]])])

In [16]:
CNOT.matrix_rep

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])

In [17]:
[
    (CNOT.matrix_rep @ kron(X, Id2) @ CNOT.matrix_rep == kron(X, Id2) @ kron(Id2, X)).all(),
    (CNOT.matrix_rep @ kron(Y, Id2) @ CNOT.matrix_rep == kron(Y, Id2) @ kron(Id2, X)).all(),
    (CNOT.matrix_rep @ kron(Z, Id2) @ CNOT.matrix_rep == kron(Z, Id2)).all(),
    (CNOT.matrix_rep @ kron(Id2, X) @ CNOT.matrix_rep == kron(Id2, X)).all(),
    (CNOT.matrix_rep @ kron(Id2, Y) @ CNOT.matrix_rep == kron(Z, Id2) @ kron(Id2, Y)).all(),
    (CNOT.matrix_rep @ kron(Id2, Z) @ CNOT.matrix_rep == kron(Z, Id2) @ kron(Id2, Z)).all(),
]

[True, True, True, True, True, True]

In [2]:
Toffoli_c0c1_t2 = QuantumGate(n = 3, free_bits_dict={}, target_bits_dict={2: X}, controlled_bits_dict={0: 1, 1: 1})
Toffoli_c0c2_t1 = QuantumGate(n = 3, free_bits_dict={}, target_bits_dict={1: X}, controlled_bits_dict={0: 1, 2: 1})
Toffoli_c1c2_t0 = QuantumGate(n = 3, free_bits_dict={}, target_bits_dict={0: X}, controlled_bits_dict={1: 1, 2: 1})

In [115]:
np.eye(16)[6].reshape(16, 1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [68]:
from numpy import zeros

In [77]:
f_is_activated = lambda bin_num, control_dict: reduce( 
                                                        lambda b1, b2: b1 & b2, 
                                                        map(lambda c: bin_num[c[0]] == str(c[1]), control_dict.items())
                                                    )

In [108]:
tmptmptmp = {2: 'b', 4: 'd', 1: 'a', 3: 'c'}

dict(sorted(tmptmptmp.items())).values()

dict_values(['a', 'b', 'c', 'd'])

In [89]:
tmp_gate = Toffoli_c1c2_t0

projector = zeros((2**tmp_gate.n, 2**tmp_gate.n))
for i in range(2**tmp_gate.n):
    num = bin(i)[2:]
    num = '0' * (tmp_gate.n - len(num)) + num
    if f_is_activated(num, tmp_gate.controlled_bits_dict):
        basis = tmp_gate.basis_kets[i].matrix_rep
        projector += (basis @ basis.T)

tmp_gate_matrix = reduce(kron, [X, Id2, Id2]) @ projector + (eye(2**tmp_gate.n) - projector)

In [91]:
67/47

1.425531914893617

In [90]:
tmp_gate_matrix

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.]])

In [93]:
%timeit Toffoli_c1c2_t0.compute_matrix_rep()

5.56 ms ± 875 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [81]:
%%timeit
QuantumGate(n = 3, free_bits_dict={}, target_bits_dict={0: X}, controlled_bits_dict={1: 1, 2: 1})

8.23 ms ± 3.31 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [94]:
Toffoli_c0c1_t2.free_bits_dict

{}

In [67]:
tmp_gate.basis_kets

[array([[1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0]]),
 array([[0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0]]),
 array([[0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0]]),
 array([[0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0]]),
 array([[0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0]]),
 array([[0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0]]),
 array([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0]]),
 array([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1]])]

In [64]:
#xxx = '11110'



%timeit f_is_activated('11100')

The slowest run took 4.16 times longer than the fastest. This could mean that an intermediate result is being cached.
4.1 µs ± 2.69 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [95]:
type(({0: 1, 2: 1, 4: 0}).items()).__name__

'dict_items'

In [30]:
for i in tmp_gate.controlled_bits_dict.items():
    print(i)

(0, 1)
(1, 1)


In [29]:
tmp_cond = lambda x, y: (x == 1) & (y == 3)
tmp_cond(1, 3)

True

In [25]:
Fredkin = array([[1, 0, 0, 0, 0, 0, 0, 0], 
                 [0, 1, 0, 0, 0, 0, 0, 0], 
                 [0, 0, 1, 0, 0, 0, 0, 0],
                 [0, 0, 0, 1, 0, 0, 0, 0],
                 [0, 0, 0, 0, 1, 0, 0, 0],
                 [0, 0, 0, 0, 0, 0, 1, 0],
                 [0, 0, 0, 0, 0, 1, 0, 0],
                 [0, 0, 0, 0, 0, 0, 0, 1]])
                  
all_combo = list(itertools.product(*[[
                                      Toffoli_c0c1_t2.matrix_rep, 
                                      Toffoli_c0c2_t1.matrix_rep, 
                                      Toffoli_c1c2_t0.matrix_rep]
                                    ] * 3))
                                    
eval_combo = list(map(lambda comb: (reduce(lambda m1, m2: m1 @ m2, comb) == Fredkin).all(), all_combo))
print(eval_combo)

[False, False, False, True, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]


In [27]:
[
    (Toffoli_c0c1_t2.matrix_rep @ Toffoli_c0c2_t1.matrix_rep @ Toffoli_c0c1_t2.matrix_rep == Fredkin).all(),
    (Toffoli_c0c2_t1.matrix_rep @ Toffoli_c0c1_t2.matrix_rep @ Toffoli_c0c2_t1.matrix_rep == Fredkin).all()
]

[True, True]

In [28]:
G1 = QuantumGate(n = 3, free_bits_dict={0: H}, target_bits_dict={}, controlled_bits_dict={})
G2 = QuantumGate(n = 3, free_bits_dict={}, target_bits_dict={0: S}, controlled_bits_dict={1: 1})
G3 = QuantumGate(n = 3, free_bits_dict={}, target_bits_dict={0: T}, controlled_bits_dict={2: 1})
G4 = QuantumGate(n = 3, free_bits_dict={1: H}, target_bits_dict={}, controlled_bits_dict={})
G5 = QuantumGate(n = 3, free_bits_dict={}, target_bits_dict={1: S}, controlled_bits_dict={2: 1})
G6 = QuantumGate(n = 3, free_bits_dict={2: H}, target_bits_dict={}, controlled_bits_dict={})


In [29]:
circuit = [G1, G2, G3, G4, G5, G6]
circuit = map(lambda gate: gate.matrix_rep, reversed(circuit))
swap = reduce(lambda m1, m2: m1 + m2, [(BasisKet(s1, s2, s3).matrix_rep @ BasisKet(s3, s2, s1).matrix_rep.T) for s1 in range(2) for s2 in range(2) for s3 in range(2)])
FT = sqrt(8) * swap @ reduce(lambda g1, g2: g1 @ g2, circuit)

In [108]:
FT

Matrix([
[1,              1,  1,              1,  1,              1,  1,              1],
[1,    exp(I*pi/4),  I,  I*exp(I*pi/4), -1,   -exp(I*pi/4), -I, -I*exp(I*pi/4)],
[1,              I, -1,             -I,  1,              I, -1,             -I],
[1,  I*exp(I*pi/4), -I,    exp(I*pi/4), -1, -I*exp(I*pi/4),  I,   -exp(I*pi/4)],
[1,             -1,  1,             -1,  1,             -1,  1,             -1],
[1,   -exp(I*pi/4),  I, -I*exp(I*pi/4), -1,    exp(I*pi/4), -I,  I*exp(I*pi/4)],
[1,             -I, -1,              I,  1,             -I, -1,              I],
[1, -I*exp(I*pi/4), -I,   -exp(I*pi/4), -1,  I*exp(I*pi/4),  I,    exp(I*pi/4)]])

In [40]:
omega = exp(I * pi / 4)
FT_res = [[1, 1, 1, 1, 1, 1, 1, 1]]
FT_res += ([[omega**p for p in range(0, i * 8, i)] for i in range(1, 8)])
FT_res = array(FT_res)
((FT_res - FT).round(10) == 0).all()

True

In [117]:
res = [[1, 1, 1, 1, 1, 1, 1, 1]]
res += ([[omega**p for p in range(0, i * 8, i)] for i in range(1, 8)])
xxx = (Matrix(res) - FT)
xxx.expand().simplify()
xxx

Matrix([
[0,                              0, 0,                              0, 0,                              0, 0,                              0],
[0,                              0, 0, -I*exp(I*pi/4) + exp(3*I*pi/4), 0,   exp(-3*I*pi/4) + exp(I*pi/4), 0,   exp(-I*pi/4) + I*exp(I*pi/4)],
[0,                              0, 0,                              0, 0,                              0, 0,                              0],
[0, -I*exp(I*pi/4) + exp(3*I*pi/4), 0,                              0, 0,   exp(-I*pi/4) + I*exp(I*pi/4), 0,   exp(-3*I*pi/4) + exp(I*pi/4)],
[0,                              0, 0,                              0, 0,                              0, 0,                              0],
[0,   exp(-3*I*pi/4) + exp(I*pi/4), 0,   exp(-I*pi/4) + I*exp(I*pi/4), 0,                              0, 0, -I*exp(I*pi/4) + exp(3*I*pi/4)],
[0,                              0, 0,                              0, 0,                              0, 0,                              0

In [ ]:
[
    G2.matrix_rep @ BasisKet(0, 0, 0).mat_rep == BasisKet(0, 0, 0).mat_rep,
    G2.matrix_rep @ BasisKet(0, 0, 1).mat_rep == BasisKet(0, 0, 1).mat_rep,
    G2.matrix_rep @ BasisKet(0, 1, 0).mat_rep == BasisKet(1, 1, 0).mat_rep,
    G2.matrix_rep @ BasisKet(0, 1, 1).mat_rep == BasisKet(1, 1, 1).mat_rep,
    G2.matrix_rep @ BasisKet(1, 0, 0).mat_rep == BasisKet(1, 0, 0).mat_rep,
    G2.matrix_rep @ BasisKet(1, 0, 1).mat_rep == BasisKet(1, 0, 1).mat_rep,
    G2.matrix_rep @ BasisKet(1, 1, 0).mat_rep == BasisKet(0, 1, 0).mat_rep,
    G2.matrix_rep @ BasisKet(1, 1, 1).mat_rep == BasisKet(0, 1, 1).mat_rep
]

In [98]:
{0: 1}|{1: 'a'}

{0: 1, 1: 'a'}